import * as core from "@actions/core";
import * as github from "@actions/github";
import { getConfig } from "./config";
import { getReviewerResult, FileChange } from "./reviewer";

async function run(): Promise<void> {
  try {
    const config = getConfig();
    const octokit = github.getOctokit(config.repoToken);
    const context = github.context;

    if (!context.payload.pull_request) {
      core.warning(
        "This action only works on pull_request or pull_request_target events",
      );
      return;
    }

    const prNumber = context.payload.pull_request.number;
    const owner = context.repo.owner;
    const repo = context.repo.repo;

    core.info(`Analyzing PR #${prNumber}...`);

    // Fetch changed files
    const files = await getChangedFiles(octokit, owner, repo, prNumber);
    core.info(`Found ${files.length} changed files`);

    // Calculate reviewer recommendation
    const result = getReviewerResult(
      files,
      config.thresholds,
      config.fileWeights,
      config.labelPrefix,
    );

    core.info(`Total lines changed: ${result.totalLines}`);
    if (config.fileWeights.length > 0) {
      core.info(`Weighted lines: ${result.weightedLines}`);
    }
    core.info(`Recommended reviewers: ${result.reviewerCount}`);

    // Set outputs
    core.setOutput("reviewer-count", result.reviewerCount.toString());
    core.setOutput("total-lines", result.totalLines.toString());
    core.setOutput("weighted-lines", result.weightedLines.toString());
    core.setOutput("label", result.label);

    // Add label
    if (config.addLabel) {
      await applyLabel(
        octokit,
        owner,
        repo,
        prNumber,
        result.label,
        config.labelPrefix,
      );
    }

    // Add comment
    if (config.addComment) {
      await addComment(octokit, owner, repo, prNumber, result);
    }

    core.info("Done!");
  } catch (error) {
    if (error instanceof Error) {
      core.setFailed(error.message);
    } else {
      core.setFailed("An unexpected error occurred");
    }
  }
}

async function getChangedFiles(
  octokit: ReturnType<typeof github.getOctokit>,
  owner: string,
  repo: string,
  prNumber: number,
): Promise<FileChange[]> {
  const files: FileChange[] = [];
  let page = 1;

  while (true) {
    const response = await octokit.rest.pulls.listFiles({
      owner,
      repo,
      pull_number: prNumber,
      per_page: 100,
      page,
    });

    for (const file of response.data) {
      files.push({
        filename: file.filename,
        additions: file.additions,
        deletions: file.deletions,
      });
    }

    if (response.data.length < 100) break;
    page++;
  }

  return files;
}

async function applyLabel(
  octokit: ReturnType<typeof github.getOctokit>,
  owner: string,
  repo: string,
  prNumber: number,
  label: string,
  labelPrefix: string,
): Promise<void> {
  // Remove any existing reviewer labels first
  const { data: existingLabels } = await octokit.rest.issues.listLabelsOnIssue({
    owner,
    repo,
    issue_number: prNumber,
  });

  for (const existing of existingLabels) {
    if (
      existing.name.startsWith(`${labelPrefix}:`) &&
      existing.name !== label
    ) {
      await octokit.rest.issues.removeLabel({
        owner,
        repo,
        issue_number: prNumber,
        name: existing.name,
      });
      core.info(`Removed old label: ${existing.name}`);
    }
  }

  // Add the new label
  await octokit.rest.issues.addLabels({
    owner,
    repo,
    issue_number: prNumber,
    labels: [label],
  });
  core.info(`Applied label: ${label}`);
}

async function addComment(
  octokit: ReturnType<typeof github.getOctokit>,
  owner: string,
  repo: string,
  prNumber: number,
  result: ReturnType<typeof getReviewerResult>,
): Promise<void> {
  const marker = "<!-- pr-reviewer-labeler -->";

  // Check for existing comment to update instead of creating duplicates
  const { data: comments } = await octokit.rest.issues.listComments({
    owner,
    repo,
    issue_number: prNumber,
  });

  const existingComment = comments.find((c) => c.body?.includes(marker));

  const body = `${marker}
## Reviewer Recommendation

| Metric | Value |
|--------|-------|
| Lines changed | ${result.totalLines} |
| Weighted lines | ${result.weightedLines} |
| **Suggested reviewers** | **${result.reviewerCount}** |

> Generated by [pr-reviewer-labeler](https://github.com/anistark/pr-reviewer-labeler)`;

  if (existingComment) {
    await octokit.rest.issues.updateComment({
      owner,
      repo,
      comment_id: existingComment.id,
      body,
    });
    core.info("Updated existing comment");
  } else {
    await octokit.rest.issues.createComment({
      owner,
      repo,
      issue_number: prNumber,
      body,
    });
    core.info("Added comment");
  }
}

run();
